apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: goserver
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: goserver
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
